<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	  <UserSecretsId>18329ca9-db5d-4291-8df0-9bd10a22b5e3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JevDotNet\JevDotNet.csproj" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.22.0" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.22.0" />
    <Content Update="Data\table-data.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Update="Data\judge-data.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Update="Data\judge-luna-cache\*.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
