// <auto-generated/>
#nullable enable
using JevDotNet.Demo.Services;

namespace JevDotNet.Demo.Components.Pages
{
    public partial class BulkSupport
    {
        private IReadOnlyList<BulkTriageMessage> Messages = [];
        private JevBulkMode Mode = JevBulkMode.Batched;
        private string BatchSize = "95";
        private bool IsBatchSizeValid => int.TryParse(BatchSize, out var size) && size is >= 2 and <= 95;
        private string SelectedDecisionModel = DemoDecisionModels.DefaultModelId;
        private BulkTriageRun? Run;
        private CancellationTokenSource? Cancellation;
        private string? LoadError;
        private string? Error;
        private bool IsBusy;
        private int Tab;

        protected override void OnInitialized()
        {
            try { Messages = Triage.LoadMessages(); }
            catch (Exception error) when (error is IOException or System.Text.Json.JsonException)
            { LoadError = error.Message; }
        }

        private async Task StartAsync()
        {
            if (IsBusy || !Triage.HasApiKey || Messages.Count == 0) return;
            if (Mode == JevBulkMode.Batched && !IsBatchSizeValid)
            {
                Error = "Enter a number from 2 to 95 for messages per Decisions request.";
                return;
            }
            Error = null;
            Tab = 0;
            Run = new BulkTriageRun(Messages, Mode, SelectedDecisionModel,
                Mode == JevBulkMode.Batched ? int.Parse(BatchSize) : 95);
            IsBusy = true;
            Cancellation = new CancellationTokenSource();
            try
            {
                await Triage.RunAsync(Run, () => InvokeAsync(StateHasChanged), Cancellation.Token);
            }
            catch (OperationCanceledException) when (Cancellation.IsCancellationRequested)
            {
                Run.Cancelled = true;
            }
            catch (Exception error)
            {
                Error = error.Message;
            }
            finally
            {
                IsBusy = false;
                Cancellation.Dispose();
                Cancellation = null;
            }
        }

        private void Cancel() => Cancellation?.Cancel();
        private void OnDecisionModelChanged() => OnRunOptionsChanged();
        private void OnRunOptionsChanged()
        {
            Run = null;
            Error = null;
        }
        public void Dispose() => Cancellation?.Cancel();
        private static string Percent(double value) => $"{value * 100:0.0}%";
        private static string Score(TriageScores? scores, string key) => scores is null ? "—" : Percent(scores.Get(key));
        private static string Duration(TimeSpan time) => $"{time.TotalSeconds:0.00} s";
        private static string SignedDuration(TimeSpan time) => $"{(time.Ticks >= 0 ? "+" : "−")}{Duration(time.Duration())}";
    }
}
